### PR TITLE
OPER-2071 Port Tapjoy changes to latest New Relic gem

### PR DESCRIPTION
**Pull request by alanbrent**
This is required work for OPER-2045, related PR [here](https://github.com/Tapjoy/tapjoyserver/pull/13217)

@Tapjoy/eng-group-ops

### CODE REVIEW

**Comment by alanbrent** [comment]
Forward-ported commit in question is [here](https://github.com/Tapjoy/rpm/commit/10b5c48bd43f2d9a622db6e7c5aa4eee90c93cbe)

**Comment by atayarani** [comment]
ping @jlogsdon since you were involved in the discussion earlier today

**Comment by alanbrent** [comment]
@jlogsdon @obrie if you could look at this, that'd be great. If you checkout my branch and run `git diff 0dfcd603acd4277a1d9da19722265a57b1499e93 lib/new_relic/agent/pipe_channel_manager.rb` that should give you the difference.

**Comment by StabbyCutyou** [comment]
This seems like a lot of changes to review.

Wondering if it'd be easier to take the current gem and try to replay our change on top of it?

**Comment by StabbyCutyou** [comment]
Actually, looks like a pretty clean merge

**Comment by alanbrent** [comment]
Mostly, yeah. I did have to resolve a conflict during rebase, but it was
reasonably straightforward.

On Wednesday, March 2, 2016, StabbyCutyou <notifications@github.com> wrote:

> Actually, looks like a pretty clean merge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Tapjoy/rpm/pull/3#issuecomment-191546599>.
>


-- 

-
Brent Stephens

**Comment by obrie** [comment]
lgtm!  Thanks for doing this!

**Comment by StabbyCutyou** [comment]
Should we do a burn-in test on chore for an hour or so, to see if the
problem recurs? I remember how to detect it.

But this looked good in general

**Comment by obrie** [comment]
You could use `chore-tester` -- I think it typically only took a few minutes to detect it using that (we can use the aws stub to avoid having to load anything into sqs).

**Comment by obrie** [comment]
It's probably worth it to at least do the `chore-tester` test before rolling this out to TJS.

**Comment by StabbyCutyou** [comment]
I was going to ping Lionel, Alvin, or Jayanth since I think they've been working on chore-tester, but they don't have access to this repo so I can't do that.

I'll drop them an email to see if they have time to help test.

**Comment by StabbyCutyou** [comment]
Jayanth is going to do some testing for us today.

**Comment by alanbrent** [comment]
Should I change the build string to something a little more indicative of custom-ness? e.g. `3.15.0.314.TJ`

**Comment by goose42** [comment]
@StabbyCutyou @obrie @alanbrent 

Ran some tests using `chore-tester`. Had this configuration:
```
c.consumer_strategy   = Chore::Strategy::ThreadedConsumerStrategy
c.worker_strategy     = Chore::Strategy::ForkedWorkerStrategy
c.batch_size          = 1
c.threads_per_queue   = 1
c.num_workers         = 10
```
Also, this was running on an Ubuntu machine, it read through 10000 messages, and the the number of open files were consistently between 62 and 64 during the entire execution.

**Comment by alanbrent** [comment]
GIMME THE THUMB

**Comment by alanbrent** [comment]
Would it be better for me to bring upstream into master with a separate PR? That would leave this PR with a single commit.

**Comment by alanbrent** [comment]
https://github.com/Tapjoy/rpm/pull/4

**Comment by obrie** [comment]
My general strategy in the past has been to:
1. Keep master up-to-date with the upstream

**Comment by obrie** [comment]
(updated comment since I hit submit a little too quickly)

**Comment by StabbyCutyou** [comment]
We add a 4th level to semver, i think, for managing our own version of someone elses gem.

So if this were 1.2.3, our version would be 1.2.3.1

**Comment by alanbrent** [comment]
Last time we just increments the build number by 1, which is what I've done
here so far. Want to go with .1 instead?

On Friday, March 4, 2016, StabbyCutyou <notifications@github.com> wrote:

> We add a 4th level to semver, i think, for managing our own version of
> someone elses gem.
>
> So if this were 1.2.3, our version would be 1.2.3.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Tapjoy/rpm/pull/3#issuecomment-192281375>.
>


-- 

-
Brent Stephens

**Comment by StabbyCutyou** [comment]
The problem is that if the existing gem is 1.2.3, and we bump our copy to 1.2.4, it now sort of conflicts with the "Real" gem if that one ever bumps to 1.2.4.

I recommend we tack on our own 4th semver particle, since it's A: compatible with the way bundler works and B: has no actual downside to it.

**Comment by alanbrent** [comment]
Of course you reply after I've just finished building a TJS slug! And yeah,
I completely agree with you and will change the build number. Which doesn't
require a change in this repo.


-
Brent Stephens

**Comment by alanbrent** [comment]
Okay, so ... should we open a pull request upstream to obviate the need for customizing this gem? If so, I'm sure I can't be the one answering their inevitable questions :)

**Comment by obrie** [comment]
Yeah I think we should be opening a PR, though I suspect that the change we've made is a workaround rather than a root cause.  It'll take a little time to gather all of the information and examples needed to have a productive conversation -- but it's something we should definitely do.

**Comment by jlogsdon** [comment]
I am pretty sure we've tried pushing this upstream before and it wasn't accepted.

**Comment by alanbrent** [comment]
FYI, the only upstream PR I found by us through a quick search was https://github.com/newrelic/rpm/pull/135, which was a previous-to-this changeset and was accepted (yay!). Oddly enough, this patch we're forward-porting was committed the same day as that PR. I imagine the intent was to go ahead and PR this one later, and it dropped out of memory.

So ... seems best to leave this ball in @obrie's court.

**Comment by obrie** [comment]
That was my understanding (according to my admittedly terrible memory) :)

I'm happy to take on the responsibility of figuring out how to get this upstream.

**Comment by StabbyCutyou** [comment]
Blackmail would be my first suggestion

**Comment by alanbrent** [comment]
FYI the activity on this PR was me updating to a recently released update, finding out it breaks TJS specs, and reverting. We're back to the previous state, and this PR is ready for thumbs.

**Pull request merged**
