### PR TITLE
Fix PipeChannelManager thread dying when IO.select raises an exception in Ruby 2.3

### PR DESCRIPTION
**Pull request by obrie**
Found that this at least seemed to allow chore-tester to run without running into the "Too many open files" issue.

/to @StabbyCutyou @riteshnoronha @Tapjoy/eng-group-ops

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
The comment in the rescue seems like a to do? Does this solve it without the cleanup code? Do we know what the exception is?

**Comment by obrie** [comment]
It's actually not a todo -- by rescuing the exception, it'll loop again and then clean up the pipes.  The exception is a socket closed error.

**Comment by StabbyCutyou** [comment]
Ah gotcha

Lgtm

**Comment by riteshnoronha** [comment]
looks reasonable to me. lgtm

**Comment by obrie** [comment]
Merging since this is what we're going with for the moment

**Pull request merged**
