### PR TITLE
Feat/upstream changes from NewRelic

### PR DESCRIPTION
**Pull request by ydderd**
Need to update our fork and release a new version of the gem to be compatible with Ruby 2.4

Ping - @obrie 
\cc - @Tapjoy/eng-group-ops

### CODE REVIEW

**Comment by obrie** [comment]
Looks good to me.  This'll also require a chore-new_relic upgrade I think to look for the new newrelic version.  To test this, I would run it through chore-tester for a few minutes and just verify that everything works as expected.

**Comment by ydderd** [comment]
Requires updates to all of our hand rolled newrelic gems/projects

- Chore-newrelic: https://github.com/Tapjoy/chore-new_relic/pull/10
- newrelic-raik: https://github.com/Tapjoy/newrelic-riak/pull/5
- newrelic-kafka: https://github.com/Tapjoy/newrelic-kafka/pull/3

**Comment by ydderd** [comment]
Tested with `chore-tester`, everything _appears_ to be working

**Comment by ydderd** [comment]
Going to merge this in unless there are any objections?

**Comment by obrie** [comment]
:shipit:

**Pull request merged**
